#include "s3m/io/point_cloud.hpp"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <stdexcept>
#include <vector>

namespace s3m {

void writePointCloudPly(const std::string& path, const cv::Mat& points, const cv::Mat& colors,
                        const cv::Mat& mask, int stride) {
    CV_Assert(points.type() == CV_32FC3);
    CV_Assert(colors.empty() || (colors.type() == CV_8UC3 && colors.size() == points.size()));
    CV_Assert(mask.empty() || (mask.type() == CV_8U && mask.size() == points.size()));
    stride = std::max(1, stride);

    struct Vertex {
        float x, y, z;
        uchar b, g, r;
    };
    std::vector<Vertex> vertices;
    vertices.reserve(static_cast<std::size_t>(points.total() / (stride * stride)));

    const bool has_color = !colors.empty();
    for (int y = 0; y < points.rows; y += stride) {
        const cv::Vec3f* p_row = points.ptr<cv::Vec3f>(y);
        const cv::Vec3b* c_row = has_color ? colors.ptr<cv::Vec3b>(y) : nullptr;
        const uchar* m_row = mask.empty() ? nullptr : mask.ptr<uchar>(y);
        for (int x = 0; x < points.cols; x += stride) {
            const cv::Vec3f& p = p_row[x];
            if (m_row) {
                if (m_row[x] == 0)
                    continue;
            } else if (!(std::isfinite(p[0]) && std::isfinite(p[1]) && std::isfinite(p[2])) ||
                       p[2] <= 0.0f) {
                continue;
            }
            Vertex v{p[0], p[1], p[2], 0, 0, 0};
            if (c_row) {
                v.b = c_row[x][0];
                v.g = c_row[x][1];
                v.r = c_row[x][2];
            } else {
                v.b = v.g = v.r = 200;
            }
            vertices.push_back(v);
        }
    }

    std::ofstream file(path);
    if (!file)
        throw std::runtime_error("writePointCloudPly: cannot open '" + path + "'");

    file << "ply\n"
         << "format ascii 1.0\n"
         << "comment generated by stereo_3d_mot\n"
         << "element vertex " << vertices.size() << "\n"
         << "property float x\nproperty float y\nproperty float z\n"
         << "property uchar red\nproperty uchar green\nproperty uchar blue\n"
         << "end_header\n";

    char line[128];
    for (const Vertex& v : vertices) {
        std::snprintf(line, sizeof(line), "%.4f %.4f %.4f %d %d %d\n", v.x, v.y, v.z,
                      static_cast<int>(v.r), static_cast<int>(v.g), static_cast<int>(v.b));
        file << line;
    }
}

}  // namespace s3m
